#[derive(Debug, Clone)]
pub enum Expansion {
    Dominion,
    Intrigue,
    Seaside,
    Alchemy,
    Prosperity,
    CornucopiaAndGuilds,
    Hinterlands,
    DarkAges,
    Adventures,
    Empires,
    Nocturne,
    Renaissance,
    Menagerie,
    Allies,
    Plunder,
    RisingSun,
    Promos,
    Custom,
}
